"""add sample_name

Revision ID: 3972894a6c68
Revises: 1b1bd7651864
Create Date: 2024-09-13 23:02:08.560451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3972894a6c68'
down_revision: Union[str, None] = '1b1bd7651864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_data', sa.Column('sample_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_data', 'sample_name')
    # ### end Alembic commands ###
