"""remove risk in report

Revision ID: 66f70c9071cc
Revises: 3972894a6c68
Create Date: 2024-09-16 10:15:27.625425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '66f70c9071cc'
down_revision: Union[str, None] = '3972894a6c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'cvd_pace_risk')
    op.drop_column('reports', 'acm_pace_risk')
    op.drop_column('reports', 'acm_horvath_risk')
    op.drop_column('reports', 'ad_horvath_risk')
    op.drop_column('reports', 'cvd_horvath_risk')
    op.drop_column('reports', 'ad_pace_risk')
    op.drop_column('reports', 'dm_pace_risk')
    op.drop_column('reports', 'cancer_pace_risk')
    op.drop_column('reports', 'cancer_horvath_risk')
    op.drop_column('reports', 'dm_horvath_risk')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('dm_horvath_risk', mysql.FLOAT(), nullable=True))
    op.add_column('reports', sa.Column('cancer_horvath_risk', mysql.FLOAT(), nullable=True))
    op.add_column('reports', sa.Column('cancer_pace_risk', mysql.FLOAT(), nullable=True))
    op.add_column('reports', sa.Column('dm_pace_risk', mysql.FLOAT(), nullable=True))
    op.add_column('reports', sa.Column('ad_pace_risk', mysql.FLOAT(), nullable=True))
    op.add_column('reports', sa.Column('cvd_horvath_risk', mysql.FLOAT(), nullable=True))
    op.add_column('reports', sa.Column('ad_horvath_risk', mysql.FLOAT(), nullable=True))
    op.add_column('reports', sa.Column('acm_horvath_risk', mysql.FLOAT(), nullable=True))
    op.add_column('reports', sa.Column('acm_pace_risk', mysql.FLOAT(), nullable=True))
    op.add_column('reports', sa.Column('cvd_pace_risk', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
