"""remove StringEncryptedType in user hashed_password

Revision ID: b70068ad2b6c
Revises: 66f70c9071cc
Create Date: 2024-09-21 03:10:57.262025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70068ad2b6c'
down_revision: Union[str, None] = '66f70c9071cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
