"""rm user and update reports and sample_data

Revision ID: c6b59ed5dbc4
Revises: 66f70c9071cc
Create Date: 2024-09-26 21:15:45.493349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c6b59ed5dbc4'
down_revision: Union[str, None] = '66f70c9071cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.add_column('reports', sa.Column('order_id', sa.Integer(), nullable=False))
    op.add_column('reports', sa.Column('vo2max', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('grip', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('gait', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('cystatin', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('adm', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('timp', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('pai1', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('packyrs', sa.Float(), nullable=True))
    op.drop_index('ix_reports_sample_id', table_name='reports')
    op.create_index(op.f('ix_reports_order_id'), 'reports', ['order_id'], unique=True)
    op.drop_constraint('reports_ibfk_1', 'reports', type_='foreignkey')
    op.drop_constraint('reports_ibfk_2', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'sample_data', ['order_id'], ['id'])
    op.drop_column('reports', 'sample_id')
    op.drop_column('reports', 'user_id')
    op.add_column('sample_data', sa.Column('biolearn_output_path', sa.String(length=255), nullable=True))
    op.add_column('sample_data', sa.Column('epigentl_output_path', sa.String(length=255), nullable=True))
    op.drop_constraint('sample_data_ibfk_1', 'sample_data', type_='foreignkey')
    op.drop_column('sample_data', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_data', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('sample_data_ibfk_1', 'sample_data', 'users', ['user_id'], ['id'])
    op.drop_column('sample_data', 'epigentl_output_path')
    op.drop_column('sample_data', 'biolearn_output_path')
    op.add_column('reports', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('sample_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_ibfk_2', 'reports', 'sample_data', ['sample_id'], ['id'])
    op.create_foreign_key('reports_ibfk_1', 'reports', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_reports_order_id'), table_name='reports')
    op.create_index('ix_reports_sample_id', 'reports', ['sample_id'], unique=True)
    op.drop_column('reports', 'packyrs')
    op.drop_column('reports', 'pai1')
    op.drop_column('reports', 'timp')
    op.drop_column('reports', 'adm')
    op.drop_column('reports', 'cystatin')
    op.drop_column('reports', 'gait')
    op.drop_column('reports', 'grip')
    op.drop_column('reports', 'vo2max')
    op.drop_column('reports', 'order_id')
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('birthday', sa.DATE(), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
